### PR TITLE
agent to centos worker

### PR DESCRIPTION
**Pull request by oshercc**

### CODE REVIEW

**Comment by romfreiman** [comment]
this repo is obsolete, isn't it?

**Comment by oshercc** [comment]
I don't think so.

**Comment by oshercc** [comment]
no, in use

**Comment by romfreiman** [comment]
no. it became obsolete today. I think

**Comment by oshercc** [comment]
ok, if this is true the image reference needs to be removed from the deployment. 
and the job needs to be cleared

**Pull request merged**
